const employeeConstants = {
    GET_ALL_EMPLOYEE_REQUEST: 'GET_ALL_EMPLOYEE_REQUEST',
    GET_ALL_EMPLOYEE_SUCCESS: 'GET_ALL_EMPLOYEE_SUCCESS',
    GET_ALL_EMPLOYEE_FAILED: 'GET_ALL_EMPLOYEE_FAILED',

    ADD_SINGLE_EMPLOYEE_REQUEST: 'ADD_SINGLE_EMPLOYEE_REQUEST',
    ADD_SINGLE_EMPLOYEE_SUCCESS: 'ADD_SINGLE_EMPLOYEE_SUCCESS',
    ADD_SINGLE_EMPLOYEE_FAILED: 'ADD_SINGLE_EMPLOYEE_FAILED',

    ADD_MULTIPLE_EMPLOYEES_REQUEST: 'ADD_MULTIPLE_EMPLOYEES_REQUEST',
    ADD_MULTIPLE_EMPLOYEES_SUCCESS: 'ADD_MULTIPLE_EMPLOYEES_SUCCESS',
    ADD_MULTIPLE_EMPLOYEES_FAILED: 'ADD_MULTIPLE_EMPLOYEES_FAILED',
};

const mailConstants = {
    SEND_MAIL_REQUEST: 'SEND_MAIL_REQUEST',
    SEND_MAIL_SUCCESS: 'SEND_MAIL_SUCCESS',
    SEND_MAIL_FAILED: 'SEND_MAIL_FAILED',
};

export { employeeConstants, mailConstants };
